dotnetnotts/dotnetnotts-web

.github/contributing.md
README.md

- Edit contribution guidelines
- Add link to Readme

Add contribution guidelines

---

.github/workflows/build_dotnetnotts.yml

- A build script in GitHub Actions to run against Pull Requests

Add Build script

---

.github/workflows/build_dotnetnotts.yml

Edit title of build action

---

.github/workflows/build_dotnetnotts.yml

- Fix build script to run on windows and not mention deploy

Change version of build command

---

.github/workflows/build_dotnetnotts.yml

Change job name

---

README.md

Short description of changes.
Screen shots of the change working
Link to any issue related to this change i.e `#9`

Fixed error while redirecting to contributing.md

---

README.md

- Added details to Readme about how to run the project locally
N/A
N/A

Update Readme to include instructions for running locally

---

Pages/Contactus.razor
Shared/NavMenu.razor
wwwroot/css/app.css
wwwroot/index.html

created contact Us page
issue #22 solved

Created Contact Us Page

---

Pages/Index.razor
Pages/Speak.razor
wwwroot/css/app.css
wwwroot/index.html

Added language to html, removed zoom limits, added structural html and took Lighthouse accessibility score from 66 to 94
#31

Accessibility Changes for Issue #31

---

Pages/LearndotNet.razor
Shared/NavMenu.razor

Added blank page to Learn .NET and linked that page to navbar
issue #7

Added blank page to Learn .NET and linked that page to navbar

---

Pages/Learn.razor
Shared/NavMenu.razor

renamed the page "learn.net" to "learn"
#39

renamed learn.net page and link to learn regarding issue #39

---

.github/contributing.md
README.md

- Update contributing information in contribution guidelines
- Update contributing information in Readme
N/A
Link to any issue related to this change: #49

Enhancement: Update contribution guidelines

---

Pages/Speak.razor
Shared/NavMenu.razor

Tabbing behavior added for Navigation and Speaker pages. Resolving issue #11 meant navigation became out of focus.
[http://g.recordit.co/twttdHVJWI.gif](http://g.recordit.co/twttdHVJWI.gif)

Tabbing behavior added for Nav & Speak

---

Pages/Index.razor
wwwroot/css/app.css

Changed sponsor to sponsor**s** since the former is a keyword for ad-blockers.
Screen shots of the change working
Link to any issue related to this change i.e #63

Fix sponsor logo display issue

---

Pages/Index.razor
wwwroot/css/app.css

Made sponsors images responsive
Desktop size :
Tablet size : 
Mobile size : 
#62

made sponsors images responsive to solve #62

---

Pages/CodeOfConduct.razor
Pages/ContactUs.razor
Pages/Index.razor
Pages/Speak.razor
Pages/SpeakerInfo.razor
Shared/Footer.razor
Shared/MainLayout.razor
Shared/NavMenu.razor
wwwroot/css/app.css
wwwroot/index.html

- Make the website work on mobile
- Add Footer
- Hamburger in top nav on smaller screen
- API call to meetup
- Events page
Best to pull down the branch locally and play with it
#70

Enhancement: Make Website Reactive

---

.github/workflows/aws_deploy_dotnetnotts.yml
.github/workflows/main_dotnetnotts.yml

Add action for deploying to AWS

Add AWS Deploy GitHub Action Script

---

wwwroot/index.html

Add Google Analytics

---

Pages/ContactUs.razor
Pages/Index.razor
Pages/Learn.razor
Pages/SpeakerInfo.razor
dotnetnotts.csproj
tests/dotnetnotts.tests.unit/ContactUsTests.cs
tests/dotnetnotts.tests.unit/EventsTests.cs
tests/dotnetnotts.tests.unit/IndexTests.cs
tests/dotnetnotts.tests.unit/LearnTests.cs
tests/dotnetnotts.tests.unit/SpeakerInfoTests.cs
tests/dotnetnotts.tests.unit/dotnetnotts.tests.unit.csproj

- Fix tests in the project
N/A

Bug: Fix tests

---

.github/workflows/build_dotnetnotts.yml
.github/workflows/main_dotnetnotts.yml

Update workflows to clean before building
See Checks
N/A

Clean before build in workflow

---

.github/workflows/build_dotnetnotts.yml
.github/workflows/main_dotnetnotts.yml
App.razor
Program.cs
dotnetnotts.csproj
global.json
tests/dotnetnotts.tests.unit/dotnetnotts.tests.unit.csproj
wwwroot/index.html

Upgraded the Main and Test project to use .NET 5.0 as per upgrade instructions found at https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio.
It has been mentioned to @wordshaker that when I had taken on the issue, the tests in the main branch were failing (9/30). I have not touched these purposely as my changes are not the cause of the failures. 
Work was done in relation to issue #78

Bump app to Net5.0

---

wwwroot/css/app.css

Increase the weight of the title for aesthetic reasons.
N/A

Increase font weight of h1

---

.github/dependabot.yml

Enhancement: Add dependabot yml

---

.github/workflows/snyk.yml

Short description of changes.
Screen shots of the change working
Link to any issue related to this change i.e `#9`

Remove on push

---

.github/workflows/build_dotnetnotts.yml
.github/workflows/main_dotnetnotts.yml
.github/workflows/snyk.yml
dotnetnotts.csproj
global.json
tests/dotnetnotts.tests.unit/dotnetnotts.tests.unit.csproj

Update Framework to .NET 6
N/A
N/A

Upgrade version and target framework

---

.github/workflows/build_dotnetnotts.yml
.github/workflows/main_dotnetnotts.yml
.github/workflows/snyk.yml
dotnetnotts.csproj
global.json
tests/dotnetnotts.tests.unit/dotnetnotts.tests.unit.csproj

Short description of changes.
Screen shots of the change working
Link to any issue related to this change i.e `#9`

Fix: Revert to .NET 5

---

.github/workflows/snyk.yml

- [Enable synk on forks](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target)
N/A
N/A

Enable Snyk builds from forks

---

.github/workflows/build_dotnetnotts.yml
.github/workflows/main_dotnetnotts.yml
dotnetnotts.csproj
global.json
tests/dotnetnotts.tests.unit/dotnetnotts.tests.unit.csproj

Upgrade website to use .NET 7
...
...

Upgrade versions to .NET 7

---

Pages/ContactUs.razor
tests/dotnetnotts.tests.unit/ContactUsTests.cs

Update Jessica's details
See code.
N/A

Update Jessica's details
